import "./globals.css";

export const metadata = {
  title: "Next App Server Rendered Time Test",
  description: "modified from code generated by `create next app`",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
